function [fitresult, gof] = createFit(xdata, ydata)
%CREATEFIT(XDATA,YDATA)
%  Create a fit.
%
%  Data for 'Fitted Line' fit:
%      X Input : xdata
%      Y Output: ydata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Feb-2020 20:14:43


%% Fit: 'Fitted Line'.
data = readmatrix("memoization.csv");
filtered = medfilt1(data,6);
xdata = filtered(:,1)
ydata = filtered(:,2)
[xData, yData] = prepareCurveData( xdata, ydata );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Fitted Line' );
x = 0:1000;
% Plot fit with data.
figure( 'Name', 'Fitted Line Dynamic' );
h(1) = plot(xData, yData, 'LineWidth',2 );
hold on
h(2) = plot(x, fitresult(x), 'LineWidth', 2);
title("Memoization")
legend( h, 'Scattered Points', 'Fitted Line', 'Location', 'SouthEast', 'Interpreter', 'none' );% Label axes
xlabel( 'Nth Sequence of Fibonacci', 'Interpreter', 'none' );
ylabel( 'Time (nanoseconds)', 'Interpreter', 'none' );
grid on
saveas(gcf, "memoization.png")
