function [fitresult, gof] = createFit(xdata, ydata)
%CREATEFIT(XDATA,YDATA)
%  Create a fit.
%
%  Data for 'Fitted Line' fit:
%      X Input : xdata
%      Y Output: ydata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Feb-2020 20:05:37
data = readmatrix("recursive.csv");
filtered = medfilt1(data,3);
xdata = filtered(:,1)
ydata = filtered(:,2)

%% Fit: 'Fitted Line'.
[xData, yData] = prepareCurveData( xdata, ydata );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [762.767096485006 1.58836692470033];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fitted Line' );
h = plot( fitresult, xData, yData );
title("Recursive")
legend( h, 'Scattered Points', 'Fitted Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Nth Sequence of Fibonacci', 'Interpreter', 'none' );
ylabel( 'Time (nanoseconds)', 'Interpreter', 'none' );
grid on
saveas(gcf, "recursive.png")


